//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Cages.ORMDataModel2
{

    public partial class PZPEDIDO : XPLiteObject
    {
        int fPEDIDO;
        public int PEDIDO
        {
            get { return fPEDIDO; }
            set { SetPropertyValue<int>(nameof(PEDIDO), ref fPEDIDO, value); }
        }
        string fO_PED;
        public string O_PED
        {
            get { return fO_PED; }
            set { SetPropertyValue<string>(nameof(O_PED), ref fO_PED, value); }
        }
        int fCODPZPEDIDO;
        [Key(true)]
        public int CODPZPEDIDO
        {
            get { return fCODPZPEDIDO; }
            set { SetPropertyValue<int>(nameof(CODPZPEDIDO), ref fCODPZPEDIDO, value); }
        }
    }

}
