//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Cages.ORMDataModel1
{

    public partial class ANDROID_CAGE : XPLiteObject
    {
        int fIDCAGE;
        [Key(true)]
        public int IDCAGE
        {
            get { return fIDCAGE; }
            set { SetPropertyValue<int>(nameof(IDCAGE), ref fIDCAGE, value); }
        }
        string fAREA;
        public string AREA
        {
            get { return fAREA; }
            set { SetPropertyValue<string>(nameof(AREA), ref fAREA, value); }
        }
        string fESTANTE;
        public string ESTANTE
        {
            get { return fESTANTE; }
            set { SetPropertyValue<string>(nameof(ESTANTE), ref fESTANTE, value); }
        }
    }

}
